# Site settings
title: aoibird
email: aoi@aoibird.com
description: >- # this means to ignore newlines until "baseurl:"
  personal homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aoibird.github.io" # the base hostname & protocol for  site
github_username: aoibird
rss: Feed
lang: zh
author: aoibird

show_excerpts: true
page_excerpts: true

permalink: /blog/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

giscus:
  enabled: true
  repo: aoibird/aoibird.github.io
  repo_id: MDEwOlJlcG9zaXRvcnkyMDE3NzM2OTA=
  category: General
  category_id: DIC_kwDODAbSes4Cbh49

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
