# Site settings
title: aoibird's blog
email: aoi@aoibird.com
description: >- # this means to ignore newlines until "baseurl:"
  personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aoibird.github.io" # the base hostname & protocol for  site
github_username: aoibird
rss: Feed

show_excerpts: true

permalink: /:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
